"""Remove copies of printjob

Revision ID: 02c9716dc56b
Revises: 4b0572f39c5b
Create Date: 2025-10-11 17:06:51.302608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '02c9716dc56b'
down_revision: Union[str, Sequence[str], None] = '4b0572f39c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'copies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('copies', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
