"""Added credit limit

Revision ID: 193a9d72a2e3
Revises: f1b48df4b6c0
Create Date: 2025-10-29 11:24:24.201154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '193a9d72a2e3'
down_revision: Union[str, Sequence[str], None] = 'f1b48df4b6c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegramadmin',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegramadmin_id'), 'telegramadmin', ['id'], unique=False)
    op.add_column('user', sa.Column('credit_limit', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'credit_limit')
    op.drop_index(op.f('ix_telegramadmin_id'), table_name='telegramadmin')
    op.drop_table('telegramadmin')
    # ### end Alembic commands ###
