"""Modify printer job model

Revision ID: 263282264ac0
Revises: 1247715a9ed4
Create Date: 2025-10-09 14:34:40.657357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '263282264ac0'
down_revision: Union[str, Sequence[str], None] = '1247715a9ed4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('cups_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_unique_constraint(None, 'printjob', ['cups_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printjob', type_='unique')
    op.drop_column('printjob', 'cups_id')
    # ### end Alembic commands ###
