"""Add file info to printjob

Revision ID: 445213ddf8b0
Revises: 8478cab0ef1a
Create Date: 2025-10-10 16:01:32.026950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '445213ddf8b0'
down_revision: Union[str, Sequence[str], None] = '8478cab0ef1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('file_id', sa.Uuid(), nullable=True))
    op.add_column('printjob', sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('printjob', sa.Column('file_size', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'printjob', 'file', ['file_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printjob', type_='foreignkey')
    op.drop_column('printjob', 'file_size')
    op.drop_column('printjob', 'file_name')
    op.drop_column('printjob', 'file_id')
    # ### end Alembic commands ###
