"""Add printer_name to printjob

Revision ID: 4b0572f39c5b
Revises: dd6fa3da7eb3
Create Date: 2025-10-11 16:22:10.699524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b0572f39c5b'
down_revision: Union[str, Sequence[str], None] = 'dd6fa3da7eb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('printer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'printer_name')
    # ### end Alembic commands ###
