"""Change JobStatus enum 2

Revision ID: 4d516fe858ee
Revises: a2ce0f32fdfe
Create Date: 2025-10-11 18:34:12.652224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4d516fe858ee'
down_revision: Union[str, Sequence[str], None] = 'a2ce0f32fdfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('status', sa.Enum('PENDING', 'HELD', 'PRINTING', 'STOPPED', 'COMPLETED', 'CANCELLED', 'ABORTED', name='jobstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'status')
    # ### end Alembic commands ###
