"""Delete printed attr on file

Revision ID: 5704e30f0e0e
Revises: ad9ad55cd4be
Create Date: 2025-10-11 21:00:13.075733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5704e30f0e0e'
down_revision: Union[str, Sequence[str], None] = 'ad9ad55cd4be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'printed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('printed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
