"""Modify users: add admin and balance

Revision ID: 71a8e003a441
Revises: c4a9ed08f270
Create Date: 2025-10-02 22:15:54.864890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '71a8e003a441'
down_revision: Union[str, Sequence[str], None] = 'c4a9ed08f270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('balance', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance')
    op.drop_column('user', 'is_admin')
    # ### end Alembic commands ###
