"""Modify users: pwd

Revision ID: 73c64f965434
Revises: 68ca15142426
Create Date: 2025-10-02 18:06:08.490599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '73c64f965434'
down_revision: Union[str, Sequence[str], None] = '68ca15142426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pwd', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('user', 'pwd')
    # ### end Alembic commands ###
