"""Modify models FIle and PrintJob, add cascade

Revision ID: 8478cab0ef1a
Revises: afb19f158d4e
Create Date: 2025-10-09 20:33:10.067707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8478cab0ef1a'
down_revision: Union[str, Sequence[str], None] = 'afb19f158d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('file_user_id_fkey'), 'file', type_='foreignkey')
    op.create_foreign_key(None, 'file', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('printjob_user_id_fkey'), 'printjob', type_='foreignkey')
    op.drop_constraint(op.f('printjob_printer_id_fkey'), 'printjob', type_='foreignkey')
    op.create_foreign_key(None, 'printjob', 'printer', ['printer_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'printjob', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'printjob', type_='foreignkey')
    op.drop_constraint(None, 'printjob', type_='foreignkey')
    op.create_foreign_key(op.f('printjob_printer_id_fkey'), 'printjob', 'printer', ['printer_id'], ['id'])
    op.create_foreign_key(op.f('printjob_user_id_fkey'), 'printjob', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'file', type_='foreignkey')
    op.create_foreign_key(op.f('file_user_id_fkey'), 'file', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
