"""Create transaction table

Revision ID: 940d5db3ce3a
Revises: 7f6ca559301f
Create Date: 2025-10-17 22:17:33.267321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '940d5db3ce3a'
down_revision: Union[str, Sequence[str], None] = '7f6ca559301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('balance_after', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'balance_after')
    # ### end Alembic commands ###
