"""Modify printer model

Revision ID: 991b473a8463
Revises: b9994814458d
Create Date: 2025-10-03 17:16:32.890932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '991b473a8463'
down_revision: Union[str, Sequence[str], None] = 'b9994814458d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('price_per_page_bw', sa.Float(), nullable=False))
    op.add_column('printer', sa.Column('admits_color', sa.Boolean(), nullable=False))
    op.add_column('printer', sa.Column('price_per_page_color', sa.Float(), nullable=False))
    op.drop_column('printer', 'price_per_page')
    op.drop_column('printer', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('printer', sa.Column('price_per_page', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('printer', 'price_per_page_color')
    op.drop_column('printer', 'admits_color')
    op.drop_column('printer', 'price_per_page_bw')
    # ### end Alembic commands ###
