"""Change JobStatus enum

Revision ID: a2ce0f32fdfe
Revises: 1676a6a92b40
Create Date: 2025-10-11 18:33:48.463858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2ce0f32fdfe'
down_revision: Union[str, Sequence[str], None] = '1676a6a92b40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('status', postgresql.ENUM('PENDING', 'PRINTING', 'COMPLETED', 'CANCELLED', 'ERROR', name='jobstatus'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
