"""Change JobStatus enum 2

Revision ID: ad9ad55cd4be
Revises: ecc0e6c22cef
Create Date: 2025-10-11 18:40:15.543903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad9ad55cd4be'
down_revision: Union[str, Sequence[str], None] = 'ecc0e6c22cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('status', sa.Enum('PENDING', 'HELD', 'PRINTING', 'STOPPED', 'COMPLETED', 'CANCELLED', 'ABORTED', name='jobstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'status')
    # ### end Alembic commands ###
