"""Create printer and printerjob models 2

Revision ID: d5e8d55ae6ac
Revises: 6e7b23f58960
Create Date: 2025-10-03 00:01:33.277983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd5e8d55ae6ac'
down_revision: Union[str, Sequence[str], None] = '6e7b23f58960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('printer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_per_page', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_printer_name'), 'printer', ['name'], unique=False)
    op.create_table('printjob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('printer_id', sa.Uuid(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=False),
    sa.Column('color', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PRINTING', 'COMPLETED', 'CANCELLED', 'ERROR', name='jobstatus'), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['printer_id'], ['printer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('printjob')
    op.drop_index(op.f('ix_printer_name'), table_name='printer')
    op.drop_table('printer')
    # ### end Alembic commands ###
