"""Modify printjob model, add copies

Revision ID: dd6fa3da7eb3
Revises: 9e003178afe1
Create Date: 2025-10-10 18:26:59.172920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd6fa3da7eb3'
down_revision: Union[str, Sequence[str], None] = '9e003178afe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printjob', sa.Column('copies', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printjob', 'copies')
    # ### end Alembic commands ###
